[package]
name = "ddbug"
version = "0.3.0"
description = "Display debugging information"
repository = "https://github.com/gimli-rs/ddbug"
readme = "../README.md"
keywords = ["debug", "DWARF"]
categories = ["development-tools::debugging"]
license = "Apache-2.0/MIT"
edition = "2018"

[dependencies]
capstone = "0.10"
capstone-sys = "0.14"
clap = "2.26"
env_logger = "0.9"
fnv = "1.0"
log = "0.4"
marksman_escape = "0.1"
memmap = "0.7"
typed-arena = "2"
parser = { package = "ddbug_parser", version = "0.3.0", path = "../parser" }

[features]
system_alloc = []
default = []
