[package]
name = "ddbug"
version = "0.3.0"
authors = ["Philip Craig <philipjcraig@gmail.com>"]
description = "Display debugging information"
repository = "https://github.com/philipc/ddbug"
readme = "README.md"
keywords = ["debug", "DWARF"]
categories = ["development-tools::debugging"]
license = "Apache-2.0/MIT"
edition = "2018"

[dependencies]
capstone = "0.7"
capstone-sys = "0.11"
clap = "2.26"
env_logger = "0.8"
fnv = "1.0"
log = "0.4"
marksman_escape = "0.1"
memmap = "0.7"
typed-arena = "2"
parser = { package = "ddbug_parser", version = "0.3.0", path = "../parser" }

[features]
system_alloc = []
default = []
